name = "Gem Pack"
author = "Taya Crystals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c48831c07db30fd00ae411e0e8c948c4c0daec95a263e0fef4e6c1d01667646a"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
