name = "Gem Pack"
author = "Taya Crystals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab53b8b83627365cda179a37d98e3f4a8999ed1f2672c29aa7cf42fc971a0cb6"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
