name = "Gem Pack"
author = "Taya Crystals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6baebba8d1261fbf55db174afeb21d5508e81cb8d280ff1810afb0dc9237052"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
