name = "Gem Pack"
author = "Taya Crystals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "555bfdb4e14bf58c21c84f040b1937cd32bbc718d6a71e76f4cdcb8a99e1eea2"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
