on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Download, install and run modpacktool from github tayadev/modpacktool with bun
      
      - uses: oven-sh/setup-bun@v2
      - run: git clone https://github.com/tayadev/modpacktool
      - run: cd modpacktool
      - run: bun install
      - run: bun run mpt.ts ../pack.lua --output ../output
      - uses: actions/upload-artifact@v2
        with:
          path: output