on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://github.com/tayadev/modpacktool/releases/download/v1.0.0/mpt
      - run: chmod +x mpt
      - run: ./mpt pack.lua # creates output directory, which should be uploaded as an artifact
      - uses: actions/upload-artifact@v2
        with:
          path: output