name: Deploy pack.toml to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'  # or newer
    
    - name: Cache Go build
      id: cache-go-build
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod  # Go module cache
          ~/.cache/go-build  # Go build cache
          ~/go/bin/packwiz  # Cached binary for packwiz
        key: ${{ runner.os }}-go-packwiz-${{ hashFiles('pack.toml') }}

    - name: Install packwiz
      if: steps.cache-go-build.outputs.cache-hit != 'true'  # Only install if cache is not hit
      run: go install github.com/packwiz/packwiz@latest

    - name: Generate Packwiz Index
      run: ~/go/bin/packwiz refresh

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload the generated files
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
