name: Deploy pack.toml to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Node.js (required for packwiz)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install packwiz
      run: npm install -g packwiz

    - name: Generate Packwiz Index
      run: packwiz refresh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Specify the directory to publish, "." or "./" to include everything
        keep_files: true  # Optional: keeps existing files on the Pages site
